baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "Using Databases in R"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-20375833-20"

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true

[params]

	author = "RStudio"
	description = ""
	copyright = ""
	
	provider = ""
	repo_url = ""

  version = "1.0.0"
  logo = "/rstudio-logo.png"
  favicon = "favicon.png"

	[params.palette]
    	primary = "rstudio-dark"
    	accent  = "orange"

    [params.font]
    	text = "sans-serif"
    	code = "Ubuntu Mono"


[[menu.main]]
  weight = 10
	name   = "Packages"
	url    = "/"
	
[[menu.main]]
  weight = 11
	name   = "dplyr"
	parent = "Packages"
	url    = "dplyr/"

[[menu.main]]
  weight = 12
	name   = "DBI"
	parent = "Packages"
	url    = "dbi/"
	
[[menu.main]]
  weight = 13
	name   = "odbc"
	parent = "Packages"
	url    = "odbc/"

[[menu.main]]
  weight = 20
	name   = "Best Practices"
	url    = "/"
	
[[menu.main]]
  weight = 21
  name = "Setting up ODBC Drivers"
  url = "drivers/"
  parent = "Best Practices"

[[menu.main]]
	weight = 22
  name   = "Run Queries Safely"
	url    = "run-queries-safely/"
	parent = "Best Practices"

[[menu.main]]
  weight = 23
	name   = "Securing Deployed Content"
	url    = "deployment/"
	parent = "Best Practices"	
	
[[menu.main]]
  weight = 24
	name   = "Securing Credentials"
	url    = "managing-credentials/"
	parent = "Best Practices"	

[[menu.main]]
  weight = 25
	name   = "Making Scripts Portable"
	url    = "portable-code/"
	parent = "Best Practices"	  

[[menu.main]]
  weight = 30
	name   = "Databases"
	url    = "/"
[[menu.main]]
  weight = 31
	name   = "MS SQL Server"
	url    = "microsoft-sql-server/"
	parent = "Databases"	
[[menu.main]]
  weight = 32
	name   = "Oracle"
	url    = "oracle/"
	parent = "Databases"	
[[menu.main]]
  weight = 33
	name   = "Hive"
	url    = "hive/"
	parent = "Databases"	
[[menu.main]]
  weight = 34
	name   = "Impala"
	url    = "impala/"
	parent = "Databases"	
[[menu.main]]
  weight = 35
	name   = "PostgreSQL"
	url    = "postgresql/"
	parent = "Databases"	
[[menu.main]]
  weight = 36
	name   = "Redshift"
	url    = "redshift/"
	parent = "Databases"
[[menu.main]]
  weight = 37
	name   = "MySQL"
	url    = "my-sql/"
	parent = "Databases"
[[menu.main]]
  weight = 38
	name   = "SQLite"
	url    = "sqlite/"
	parent = "Databases"
	[[menu.main]]
  weight = 39
	name   = "Big Query"
	url    = "big-query/"
	parent = "Databases"
[[menu.main]]
  weight = 40
	name   = "Other Databases"
	url    = "other-databases/"
	parent = "Databases"

[[menu.main]]
  weight = 50
	name   = "Advanced"
	url    = "/"

[[menu.main]]
  weight = 51
	name   = "DBI Backend"
	parent = "Advanced"
	url    = "/backend"
	
[[menu.main]]
  weight = 52
	name   = "SQL Translation"
	parent = "Advanced"
	url    = "/translation"
	
[[menu.main]]
  weight = 60
	name   = "Other Resources"
	url    = "/"

[[menu.main]]
  weight = 61
	name   = "Media"
	parent = "Other Resources"
	url    = "/media"	
	
[social]
	twitter = "rstudio"
	github  = "rstudio"
	email   = "info@rstudio.com"


