baseurl = "https://db.rstudio.com/"
languageCode = "en-us"
title = "Databases using R"
theme = "rstudio-docs-theme"
metadataformat = "yaml"
pluralizeListTitles =   "false"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-20375833-3"
[params]
	author = "RStudio"
	description = ""
	copyright = ""
	provider = ""
	repo_url = ""
  version = "1.0.0"
  logo = "/rstudio-logo.png"
  favicon = "favicon.png"
	[params.palette]
    	primary = "rstudio-dark"
    	accent  = "orange"
  [params.font]
  	text = "sans-serif"
  	code = "Ubuntu Mono"
[[menu.main]]
  weight = 1
  name = "Getting Started"
  url = "/getting-started/"
[[menu.main]]
  weight = 2
  name = "Overview"
  url = "/getting-started/overview"
  parent = "Getting Started"
[[menu.main]]
  weight = 3
  name = "Connect to a Database"
  url = "/getting-started/connect-to-database"
  parent = "Getting Started"
[[menu.main]]
  weight = 4
  name = "Database Queries"
  url = "/getting-started/database-queries"
  parent = "Getting Started"
[[menu.main]]
  weight = 10
	name   = "R Packages"
  url = "/r-packages/"
[[menu.main]]
  weight = 11
	name   = "odbc"
	url    = "/r-packages/odbc/"
	parent = "R Packages"
[[menu.main]]
  weight = 12
	name   = "DBI"
	url    = "/r-packages/dbi/"
	parent = "R Packages"
[[menu.main]]
  weight = 13
	name   = "dplyr"
	url    = "/r-packages/dplyr/"
	parent = "R Packages"
[[menu.main]]
  weight = 14
	name   = "pool"
	url    = "/r-packages/pool/"
	parent = "R Packages"
[[menu.main]]
  weight = 17
	name   = "Tooling"
	url    = "/tooling/"
[[menu.main]]
  weight = 18
	name   = "Connections Pane"
	url    = "/tooling/connections/"	
	parent = "Tooling"
[[menu.main]]
  weight = 19
	name   = "Professional Drivers"
	url    = "/tooling/pro-drivers/"
	parent = "Tooling"
[[menu.main]]
  weight = 20
	name   = "Best Practices"
	url    = "/best-practices/"
[[menu.main]]
  weight = 21
  name = "Setting up ODBC Drivers"
  url    = "/best-practices/drivers/"
  parent = "Best Practices"
[[menu.main]]
	weight = 22
  name   = "Run Queries Safely"
	url    = "/best-practices/run-queries-safely/"
	parent = "Best Practices"
[[menu.main]]
  weight = 23
	name   = "Securing Deployed Content"
	url    = "/best-practices/deployment/"
	parent = "Best Practices"	
	
[[menu.main]]
  weight = 24
	name   = "Securing Credentials"
	url    = "/best-practices/managing-credentials/"
	parent = "Best Practices"	
[[menu.main]]
  weight = 25
	name   = "Making Scripts Portable"
	url    = "/best-practices/portable-code/"
	parent = "Best Practices"	  
[[menu.main]]
  weight = 26
	name   = "Creating Visualizations"
	url    = "/best-practices/visualization/"
	parent = "Best Practices"	  
[[menu.main]]
  weight = 27
	name   = "Selecting a database interface"
	url    = "/best-practices/select-interface/"
	parent = "Best Practices"	  
[[menu.main]]
  weight = 28
	name   = "Enterprise-ready dashboards"
	url    = "/best-practices/dashboards/"
	parent = "Best Practices"	
[[menu.main]]
  weight = 29
	name   = "Schema selection"
	url    = "/best-practices/schema/"
	parent = "Best Practices"	 
[[menu.main]]
  weight = 30
	name   = "Databases"
	url    = "/databases/"
[[menu.main]]
  weight = 31
	name   = "MS SQL Server"
	url    = "/databases/microsoft-sql-server/"
	parent = "Databases"	
[[menu.main]]
  weight = 32
	name   = "Oracle"
	url    = "/databases/oracle/"
	parent = "Databases"	
[[menu.main]]
  weight = 33
	name   = "Teradata"
	url    = "/databases/teradata/"
	parent = "Databases"		
[[menu.main]]
  weight = 34
	name   = "Hive"
	url    = "/databases/hive/"
	parent = "Databases"	
[[menu.main]]
  weight = 35
	name   = "Impala"
	url    = "/databases/impala/"
	parent = "Databases"	
[[menu.main]]
  weight = 36
	name   = "PostgreSQL"
	url    = "/databases/postgresql/"
	parent = "Databases"	
[[menu.main]]
  weight = 37
	name   = "Redshift"
	url    = "/databases/redshift/"
	parent = "Databases"
[[menu.main]]
  weight = 38
	name   = "Salesforce"
	url    = "/databases/salesforce/"
	parent = "Databases"
[[menu.main]]
  weight = 39
	name   = "MySQL"
	url    = "/databases/my-sql/"
	parent = "Databases"
[[menu.main]]
  weight = 40
	name   = "MonetDB"
	url    = "/databases/monetdb/"
	parent = "Databases"
[[menu.main]]
  weight = 41
	name   = "SQLite"
	url    = "/databases/sqlite/"
	parent = "Databases"
[[menu.main]]
  weight = 42
	name   = "Big Query"
	url    = "/databases/big-query/"
	parent = "Databases"
[[menu.main]]
  weight = 43
	name   = "Athena"
	url    = "/databases/athena/"
	parent = "Databases"
[[menu.main]]
  weight = 44
	name   = "MongoDB"
	url    = "/databases/mongodb/"
	parent = "Databases"		
[[menu.main]]
  weight = 45
	name   = "Netezza"
	url    = "/databases/netezza/"
	parent = "Databases"		
[[menu.main]]
  weight = 46
	name   = "Cassandra"
	url    = "/databases/cassandra/"
	parent = "Databases"		
[[menu.main]]
  weight = 47
	name   = "Snowflake"
	url    = "/databases/snowflake/"
	parent = "Databases"		
[[menu.main]]
  weight = 49
	name   = "Other Databases"
	url    = "/databases/other-databases/"
	parent = "Databases"
[[menu.main]]
  weight = 50
	name   = "Advanced"
	url    = "/advanced/"
[[menu.main]]
  weight = 51
	name   = "DBI Backend"
	parent = "Advanced"
	url    = "/advanced/backend/"
[[menu.main]]
  weight = 52
	name   = "SQL Translation"
	parent = "Advanced"
	url    = "/advanced/translation/"
[[menu.main]]
  weight = 52
	name   = "Connection Contract"
	parent = "Advanced"
	url    = "/advanced/contract/"
[[menu.main]]
  weight = 52
	name   = "Connection Snippet"
	parent = "Advanced"
	url    = "/advanced/snippets/"
[[menu.main]]
  weight = 60
	name   = "Other Resources"
	url    = "/other-resources/"
[[menu.main]]
  weight = 61
	name   = "Media"
	parent   = "Other Resources"
	url    = "/other-resources/media/"
[social]
	twitter = "rstudio"
	github  = "rstudio"
	email   = "info@rstudio.com"
